# Translation of Odoo Server.
# This file contains the translation of the following modules:
# * account_yodlee
# 
# Translators:
# Martin Trigaux <mat@odoo.com>, 2017
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server 10.saas~18+e\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2017-09-20 11:33+0000\n"
"PO-Revision-Date: 2017-09-20 11:33+0000\n"
"Last-Translator: Martin Trigaux <mat@odoo.com>, 2017\n"
"Language-Team: Amharic (https://www.transifex.com/odoo/teams/41243/am/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"
"Language: am\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:103
#: code:addons/account_yodlee/models/yodlee.py:108
#, python-format
msgid "(Diagnostic: %r for URL %s)"
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:410
#, python-format
msgid ""
"Account Already Registered (436):Your Auto-Registration could not be "
"completed because the site reports that your account is already registered."
"  Please log in to the site to confirm and then complete the site addition "
"process with the correct login information."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:397
#, python-format
msgid ""
"Account Locked (407): We could not update your account because it appears "
"your account has been locked. This usually results from too many "
"unsuccessful login attempts in a short period of time. Please visit the site"
" or contact its customer support to resolve this issue.  Once done, please "
"update your account credentials in case they are changed."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:424
#, python-format
msgid ""
"Account Not Found(408): We're sorry, we couldn't find any accounts for you "
"at the site. Please log in at the site and confirm that your account is set "
"up, then try again."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:402
#, python-format
msgid ""
"Account Reported Closed (422): We were unable to update your account "
"information because it appears one or more of your related accounts have "
"been closed.  Please deactivate or delete the relevant account and try "
"again."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:399
#, python-format
msgid ""
"Account Type Not Supported(417):The type of account we found is not "
"currently supported.  Please remove this site and add as a  manual account."
msgstr ""

#. module: account_yodlee
#: model:ir.model.fields,help:account_yodlee.field_account_online_journal_yodlee_account_status
msgid "Active/Inactive on Yodlee system"
msgstr ""

#. module: account_yodlee
#: model:ir.model.fields,help:account_yodlee.field_account_online_provider_yodlee_additional_status
msgid "Additional information on status"
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:432
#, python-format
msgid "An Error has occurred (code %s)"
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:317
#: code:addons/account_yodlee/models/yodlee.py:319
#, python-format
msgid ""
"An error has occurred while trying to refresh accounts (type not supported)"
msgstr ""

#. module: account_yodlee
#: model:ir.model,name:account_yodlee.model_res_company
msgid "Companies"
msgstr "ድርጅት"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:160
#, python-format
msgid "Could not retrieve login form for siteId: %s (%s)"
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:394
#, python-format
msgid ""
"Credential Re-Verification Required (402): We could not update your account "
"because your username and/or password were reported to be incorrect.  Please"
" re-verify your username and password."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:400
#, python-format
msgid ""
"Credential Re-Verification Required (420):The site has merged with another. "
"Please re-verify your credentials at the site and update the same."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:311
#, python-format
msgid ""
"Different error have occurred on different accounts, see provider account "
"message for details"
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:102
#, python-format
msgid "Error %s, message: %s, reference code: %s"
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:393
#, python-format
msgid ""
"Home Value Not Found (511): The site is unable to provide home value for "
"your property. We suggest you to delete this site."
msgstr ""

#. module: account_yodlee
#: model:ir.model,name:account_yodlee.model_account_online_journal
msgid "Interface for online account journal"
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:401
#, python-format
msgid ""
"Invalid Language Setting (421): The language setting for your site account "
"is not English. Please visit the site and change the language setting to "
"English."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:416
#, python-format
msgid ""
"MFA error: Additional Authentication Enrollment Required (521) : Please "
"enroll in the new security authentication system, <Account Name> has "
"introduced. Ensure your account settings in <Cobrand> are updated with this "
"information."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:419
#, python-format
msgid ""
"MFA error: Authentication Information Expired (524):We're sorry, the "
"authentication information you provided has expired. Please try again."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:415
#, python-format
msgid ""
"MFA error: Authentication Information Incorrect (520):We're sorry, the site "
"indicates that the additional authentication information you provided is "
"incorrect. Please try updating your account again."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:418
#, python-format
msgid ""
"MFA error: Authentication Information Incorrect (523):We're sorry, the "
"authentication information you  provided is incorrect. Please try again."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:414
#, python-format
msgid ""
"MFA error: Authentication Information Required (519): Your account was not "
"updated as your authentication information like security question and answer"
" was unavailable or incomplete. Please update your account settings."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:413
#, python-format
msgid ""
"MFA error: Authentication Information Unavailable (518):Your account was not"
" updated as the required additional authentication information was "
"unavailable. Please try now."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:420
#, python-format
msgid ""
"MFA error: Credential Re-Verification Required (526): We could not update "
"your account because your username/password or additional security "
"credentials are incorrect. Please try again."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:431
#, python-format
msgid ""
"MFA error: Problem Updating Account (525): We could not update your account "
"for technical reasons. This type of error is usually resolved in a few days."
" We apologize for the inconvenience. Please try again later."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:417
#, python-format
msgid ""
"MFA error: Request Timed Out (522) :Your request has timed out as the "
"required security information was unavailable or was not provided within the"
" expected time. Please try again."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:429
#, python-format
msgid ""
"MFA error: Site Device Information Expired(509): We're sorry, we can't "
"update your account because your token is no longer valid at the site. "
"Please update your information and try again, or contact customer support."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:385
#, python-format
msgid ""
"Multiple User Logins(416): We attempted to update your account, but another "
"session was already established at the same time.  If you are currently "
"logged on to this account directly, please log off and try after some time"
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:411
#, python-format
msgid ""
"New Login Information Required(506):We're sorry, to log in to this site, you"
" need to provide additional information. Please update your account and try "
"again."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:387
#, python-format
msgid ""
"No Account Found (423): We were unable to detect an account. Please verify "
"that you account information is available at this time and If the problem "
"persists, please contact customer support at online@odoo.com for further "
"assistance."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:412
#, python-format
msgid ""
"No Payees Found(512):Your request cannot be completed as no payees were "
"found in your account."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:48
#, python-format
msgid "Please configure an email in the company settings."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:145
#, python-format
msgid "Please enter at least 3 characters for the search"
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:198
#, python-format
msgid "Please fill all required fields"
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:396
#, python-format
msgid ""
"Problem Updating Account (406): We could not update your account because the"
" site requires you to perform some additional action. Please visit the site "
"or contact its customer support to resolve this issue. Once done, please "
"update your account credentials in case they are changed else try again."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:430
#, python-format
msgid ""
"Problem Updating Account (517) :We'resorry, there was a technical problem "
"updating your account. Please try again."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:421
#, python-format
msgid ""
"Problem Updating Account(401):We're sorry, your request timed out. Please "
"try again."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:422
#, python-format
msgid ""
"Problem Updating Account(403):We're sorry, there was a technical problem "
"updating your account. This kind of error is usually resolved in a few days."
" Please try again later."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:423
#, python-format
msgid ""
"Problem Updating Account(404):We're sorry, there was a technical problem "
"updating your account. Please try again later."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:381
#, python-format
msgid ""
"Problem Updating Account(409): We could not update your account because the "
"end site is experiencing technical difficulties."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:383
#, python-format
msgid ""
"Problem Updating Account(412): We could not update your account because the "
"site is experiencing technical difficulties."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:425
#, python-format
msgid ""
"Problem Updating Account(413):We're sorry, we couldn't update your account "
"at the site because of a technical issue. This type of problem is usually "
"resolved in a few days. Please try again later."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:384
#, python-format
msgid ""
"Problem Updating Account(415): We could not update your account because the "
"site is experiencing technical difficulties."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:386
#, python-format
msgid ""
"Problem Updating Account(418): We could not update your account because the "
"site is experiencing technical difficulties. Please try later."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:426
#, python-format
msgid ""
"Problem Updating Account(419):We're sorry, we couldn't update your account "
"because of unexpected variations at the site. This kind of problem is "
"usually resolved in a few days. Please try again later."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:389
#, python-format
msgid ""
"Problem Updating Account(425): We could not update your account because the "
"site is experiencing technical difficulties. Please try later."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:390
#, python-format
msgid ""
"Problem Updating Account(426): We could not update your account for "
"technical reasons. This type of error is usually resolved in a few days. We "
"apologize for the inconvenience."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:427
#, python-format
msgid ""
"Problem Updating Account(507):We're sorry, Yodlee has just started providing"
" data updates for this site, and it may take a few days to be successful as "
"we get started. Please try again later."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:392
#, python-format
msgid ""
"Property Record Not Found (510): The site is unable to find any property "
"information for your address. Please verify if the property address you have"
" provided is correct."
msgstr ""

#. module: account_yodlee
#: model:ir.model,name:account_yodlee.model_account_online_provider
msgid "Provider for online account synchronization"
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:405
#, python-format
msgid ""
"Re-Verification Required (429): We could not update your account due to the "
"site requiring you to verify your personal information. Please log in to the"
" site and update the fields required."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:403
#, python-format
msgid ""
"Re-verification Required (427): We could not update your account due to the "
"site requiring you to view a new promotion. Please log in to the site and "
"click through to your account overview page to update the account.  We "
"apologize for the inconvenience."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:404
#, python-format
msgid ""
"Re-verification Required (428): We could not update your account due to the "
"site requiring you to accept a new Terms & Conditions. Please log in to the "
"site and read and accept the T&C."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:407
#, python-format
msgid ""
"Registration Requires Attention (433): Auto registration is not complete. "
"Please complete your registration at the end site. Once completed, please "
"complete adding this account."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:408
#, python-format
msgid ""
"Registration Requires Attention (434): Your Auto-Registration could not be "
"completed and requires further input from you.  Please re-verify your "
"registration information to complete the process."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:409
#, python-format
msgid ""
"Registration Requires Attention (435): Your Auto-Registration could not be "
"completed and requires further input from you.  Please re-verify your "
"registration information to complete the process."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:428
#, python-format
msgid ""
"Request Timed Out (508): We are sorry, your request timed out due to "
"technical reasons. Please try again."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:398
#, python-format
msgid ""
"Requested Account Type Not Found (414): We could not find your requested "
"account. You may have selected a similar site under a different category by "
"accident in which case you should select the correct site."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:388
#, python-format
msgid ""
"Site Down for Maintenance(424):We were unable to update your account as the "
"site is temporarily down for maintenance. We apologize for the "
"inconvenience.  This problem is typically resolved in a few hours. Please "
"try later."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:382
#, python-format
msgid ""
"Site No Longer Available (411):The site no longer provides online services "
"to its customers.  Please delete this account."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:406
#, python-format
msgid ""
"Site No Longer Supported (430):This site is no longer supported for data "
"updates. Please deactivate or delete your account. We apologize for the "
"inconvenience."
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:391
#, python-format
msgid ""
"Site Not Supported (505): We currently does not support the security system "
"used by this site. We apologize for any inconvenience. Check back "
"periodically if this situation has changed."
msgstr ""

#. module: account_yodlee
#: model:ir.model.fields,help:account_yodlee.field_account_online_provider_yodlee_next_schedule_refresh
msgid "Technical field: scheduled time for yodlee to perform an update"
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:273
#: code:addons/account_yodlee/models/yodlee.py:274
#, python-format
msgid "Timeout: Could not retrieve accounts informations"
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:60
#: code:addons/account_yodlee/models/yodlee.py:73
#: code:addons/account_yodlee/models/yodlee.py:87
#: code:addons/account_yodlee/models/yodlee.py:133
#, python-format
msgid "Timeout: the server did not reply within 30s"
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:395
#, python-format
msgid ""
"Update Request Canceled(405):Your account was not updated because you "
"canceled the request."
msgstr ""

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_account_online_journal_yodlee_account_status
msgid "Yodlee Account Status"
msgstr ""

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_account_online_provider_yodlee_additional_status
msgid "Yodlee Additional Status"
msgstr ""

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_account_online_provider_yodlee_last_attempted_refresh
msgid "Yodlee Last Attempted Refresh"
msgstr ""

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_account_online_provider_yodlee_next_schedule_refresh
msgid "Yodlee Next Schedule Refresh"
msgstr ""

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_account_online_journal_yodlee_status_code
msgid "Yodlee Status Code"
msgstr ""

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_res_company_yodlee_user_access_token
msgid "Yodlee access token"
msgstr ""

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_res_company_yodlee_user_login
msgid "Yodlee login"
msgstr ""

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_res_company_yodlee_user_password
msgid "Yodlee password"
msgstr ""

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_res_company_yodlee_access_token
msgid "access_token"
msgstr ""
