# Translation of Odoo Server.
# This file contains the translation of the following modules:
# 	* account_yodlee
# 
# Translators:
# Mustafa Rawi <mustafa@cubexco.com>, 2019
# Mustafa J. Kadhem <safi2266@gmail.com>, 2019
# Osoul <baruni@osoul.ly>, 2019
# Abd El-Rahman Ali <abdelrahman.ali.242@gmail.com>, 2019
# 
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server saas~12.5+e\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-08-26 08:04+0000\n"
"PO-Revision-Date: 2019-08-26 09:34+0000\n"
"Last-Translator: Abd El-Rahman Ali <abdelrahman.ali.242@gmail.com>, 2019\n"
"Language-Team: Arabic (https://www.transifex.com/odoo/teams/41243/ar/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"
"Language: ar\n"
"Plural-Forms: nplurals=6; plural=n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 && n%100<=99 ? 4 : 5;\n"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "(Diagnostic: %r for URL %s)"
msgstr "(التشخيص: %r للرابط: %s)"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Account"
msgstr "الحساب"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Account Already Registered (436):Your Auto-Registration could not be "
"completed because the site reports that your account is already registered."
"  Please log in to the site to confirm and then complete the site addition "
"process with the correct login information."
msgstr ""
"تم تسجيل الحساب بالفعل (436): لم يكتمل تسجيلك التلقائي لأن حسابك مسجل "
"بالفعل. برجاء تسجيل الدخول للموقع للتأكد ثم أكمل عملية إضافة الموقع ببيانات "
"تسجيل الدخول الصحيحة."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Account Locked (407): We could not update your account because it appears "
"your account has been locked. This usually results from too many "
"unsuccessful login attempts in a short period of time. Please visit the site"
" or contact its customer support to resolve this issue.  Once done, please "
"update your account credentials in case they are changed."
msgstr ""
"الحساب مغلق (407): تعذّر تحديث حسابك لأنه يبدو مغلقًا. عادة يكون هذا بسبب "
"عدة محاولات تسجيل دخول فاشلة خلال فترة زمنية قصيرة. برجاء زيارة الموقع أو "
"التواصل مع خدمة العملاء لحل هذه المشكلة. بمجرد الانتهاء، برجاء تحديث بيانات "
"اعتماد حسابك في حال تم تغييرها."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Account Not Found(408): We're sorry, we couldn't find any accounts for you "
"at the site. Please log in at the site and confirm that your account is set "
"up, then try again."
msgstr ""
"الحساب غير موجود (408): نعتذر، تعذّر إيجاد أي حسابات لك في الموقع. برجاء "
"تسجيل دخولك للموقع والتأكد من أن حسابك مضبوط، ثم حاول مجددًا."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Account Reported Closed (422): We were unable to update your account "
"information because it appears one or more of your related accounts have "
"been closed.  Please deactivate or delete the relevant account and try "
"again."
msgstr ""
"إخطار بإغلاق الحساب (422): تعذّر تحديث بيانات حسابك بسبب إغلاق إحدى حساباتك "
"المرتبطة به على الأقل. برجاء تعطيل الحساب المذكور أو حذفه ثم المحاولة "
"مجددًا."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Account Type Not Supported(417):The type of account we found is not "
"currently supported.  Please remove this site and add as a  manual account."
msgstr ""
"نوع الحساب غير مدعوم (417): نوع الحساب الذي وجدناه غير مدعوم حاليًا. برجاء "
"إزالة الموقع وإضافته كحساب عادي."

#. module: account_yodlee
#: model:ir.model.fields,help:account_yodlee.field_account_online_journal__yodlee_account_status
msgid "Active/Inactive on Yodlee system"
msgstr "نشط/غير نشط على نظام Yodlee"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "An Error has occurred (code %s)"
msgstr "حدث خطأ (الكود %s)"

#. module: account_yodlee
#: model:ir.model,name:account_yodlee.model_res_company
msgid "Companies"
msgstr "الشركات"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Could not make sense of parameters: %s"
msgstr "تعذّر فهم الباراميتر: %s"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Credential Re-Verification Required (402): We could not update your account "
"because your username and/or password were reported to be incorrect.  Please"
" re-verify your username and password."
msgstr ""
"مطلوب إعادة التأكد من بيانات اعتمادك (402): تعذّر تحديث حسابك لوجود خطأ في "
"الاسم و/أو كلمة المرور. برجاء التأكد من اسم المستخدم وكلمة المرور."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Credential Re-Verification Required (420):The site has merged with another. "
"Please re-verify your credentials at the site and update the same."
msgstr ""
"مطلوب إعادة التأكد من بيانات اعتمادك (420): لقد اندمج الموقع مع موقع آخر. "
"برجاء إعادة التأكد من بيانات اعتمادك على الموقع وتحديثها."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Error %s, message: %s"
msgstr "خطأ %s، الرسالة: %s"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Error %s, message: %s, reference code: %s"
msgstr "خطأ %s، الرسالة: %s، الكود المرجعي: %s"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Home Value Not Found (511): The site is unable to provide home value for "
"your property. We suggest you to delete this site."
msgstr ""
"تعذّر العثور على قيمة للمنزل (511): لم يستطع الموقع حساب قيمة ملكيتك. نقترح "
"عليك حذف هذا الموقع."

#. module: account_yodlee
#: model:ir.model,name:account_yodlee.model_account_online_journal
msgid "Interface for Online Account Journal"
msgstr "واجهة دفتر يومية الحساب الإلكتروني"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Invalid Language Setting (421): The language setting for your site account "
"is not English. Please visit the site and change the language setting to "
"English."
msgstr ""
"إعدادات اللغة غير صحيحة (421): لغة حسابك ليست إنجليزية. برجاء زيارة الموقع "
"وتغيير إعداد اللغة ليكون بالإنجليزية."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Additional Authentication Enrollment Required (521) : Please "
"enroll in the new security authentication system, <Account Name> has "
"introduced. Ensure your account settings in <Cobrand> are updated with this "
"information."
msgstr ""
"خطأ MFA: مطلوب بيانات مُصادقة إضافية (521): برجاء الالتحاق بنظام المُصادقة "
"الأمنية الجديد الذي قدمه <Account Name>. تأكد من تحديث إعدادات حسابك على "
"<Cobrand> بهذه المعلومات."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Authentication Information Expired (524):We're sorry, the "
"authentication information you provided has expired. Please try again."
msgstr ""
"خطأ MFA: بيانات المُصادقة منتهية الصلاحية (524): نعتذر، انتهت صلاحية بيانات "
"المُصادقة التي أدخلتها. برجاء المحاولة مجددًا."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Authentication Information Incorrect (520):We're sorry, the site "
"indicates that the additional authentication information you provided is "
"incorrect. Please try updating your account again."
msgstr ""
"خطأ MFA: بيانات المُصادقة خطأ (520): نعتذر، يشير الموقع إلى أن بيانات "
"المُصادقة الإضافية التي أدخلتها غير صحيحة. برجاء محاولة تحديث حسابك مجددًا."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Authentication Information Incorrect (523):We're sorry, the "
"authentication information you  provided is incorrect. Please try again."
msgstr ""
"خطأ MFA: بيانات المُصادقة خطأ (523): نعتذر، بيانات المُصادقة التي أدخلتها "
"غير صحيحة. برجاء المحاولة مجددًا."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Authentication Information Required (519): Your account was not "
"updated as your authentication information like security question and answer"
" was unavailable or incomplete. Please update your account settings."
msgstr ""
"خطأ MFA: بيانات المُصادقة مطلوبة (519): لم يتم تحديث حسابك لأن بيانات "
"مُصادقتك كالسؤال الأمني وإجابته كانت ناقصة أو خاطئة. برجاء تحديث إعدادات "
"الحساب."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Authentication Information Unavailable (518):Your account was not"
" updated as the required additional authentication information was "
"unavailable. Please try now."
msgstr ""
"خطأ MFA: بيانات المُصادقة غير متاحة (518):  لم يتم تحديث حسابك لعدم توفر "
"بيانات المُصادقة الإضافية المطلوبة. برجاء المحاولة الآن."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Credential Re-Verification Required (526): We could not update "
"your account because your username/password or additional security "
"credentials are incorrect. Please try again."
msgstr ""
"خطأ MFA: مطلوب إعادة التأكد من بيانات اعتمادك (526): تعذّر تحديث حسابك لوجود"
" خطأ في اسم المستخدم/كلمة المرور أو بيانات الاعتماد الأمنية الإضافية. برجاء "
"المحاولة مجددًا."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Problem Updating Account (525): We could not update your account "
"for technical reasons. This type of error is usually resolved in a few days."
" We apologize for the inconvenience. Please try again later."
msgstr ""
"خطأ MFA: حدثت مشكلة أثناء تحديث حسابك (525): تعذّر تحديث حسابك لأسباب تقنية."
" عادة تُحل هذه المشاكل خلال بضعة أيام. نعتذر على الإزعاج. برجاء المحاولة "
"مجددًا لاحقًا."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Request Timed Out (522) :Your request has timed out as the "
"required security information was unavailable or was not provided within the"
" expected time. Please try again."
msgstr ""
"خطأ MFA: انتهت مهلة الطلب (522): لقد انتهت مهلة طلبك لأن البيانات الأمنية "
"المطلوبة لم تكن مُتاحة أو لم تتوفر خلال الوقت المتوقع. برجاء المحاولة "
"مجددًا."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Site Device Information Expired(509): We're sorry, we can't "
"update your account because your token is no longer valid at the site. "
"Please update your information and try again, or contact customer support."
msgstr ""
"خطأ MFA: انتهت صلاحية بيانات موقع الجهاز (509): نعتذر، تعذّر تحديث حسابك لأن"
" كلمة سرك لم تعد صالحة على الموقع. برجاء تحديث بيانات ثم المحاولة مجددًا، أو"
" تحدث مع خدمة العملاء."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Multiple User Logins(416): We attempted to update your account, but another "
"session was already established at the same time.  If you are currently "
"logged on to this account directly, please log off and try after some time"
msgstr ""
"عمليات تسجيل دخول متعددة للمستخدم (416): حاولنا تحديث حسابك، لكن هناك جلسة "
"عمل أخرى مُفعلة في نفس الوقت. إذا كنت قد قمت بتسجيل الدخول لهذا الحساب "
"مباشرةً، فبرجاء تسجيل الخروج والمحاولة لاحقًا"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"New Login Information Required(506):We're sorry, to log in to this site, you"
" need to provide additional information. Please update your account and try "
"again."
msgstr ""
"مطلوب معلومات جديدة لتسجيل الدخول (506): معتذر، لتسجل دخولك في هذا الموقع، "
"تحتاج لتسجيل معلومات إضافية. برجاء تحديث حسابك والمحاولة مجددًا."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"No Account Found (423): We were unable to detect an account. Please verify "
"that you account information is available at this time and If the problem "
"persists, please contact customer support at online@odoo.com for further "
"assistance."
msgstr ""
"لم يُعثر على حساب (423): تعذّر إيجاد حساب. برجاء التحقق من توفر بيانات حسابك"
" حاليًا. إذا استمرت المشكلة، برجاء التواصل مع خدمة العملاء على البريد "
"الإلكتروني online@odoo.com للحصول على مساعدة."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"No Payees Found(512):Your request cannot be completed as no payees were "
"found in your account."
msgstr ""
"تعذّر العثور على مستفيد (512): لا يمكن إنهاء طلبك لأننا لم نعثر على مستفيد "
"في حسابك."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Online institution"
msgstr "مؤسسة إلكترونية"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Please configure an email in the company settings."
msgstr "برجاء تعيين بريد إلكتروني في إعدادات الشركة."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account (406): We could not update your account because the"
" site requires you to perform some additional action. Please visit the site "
"or contact its customer support to resolve this issue. Once done, please "
"update your account credentials in case they are changed else try again."
msgstr ""
"حدثت مشكلة أثناء تحديث حسابك (406): تعذّر تحديث حسابك لأن هناك إجراءات أخرى "
"مطلوبة. برجاء زيارة الموقع أو تواصل مع خدمة العملاء لحل هذه المشكلة. بمجرد "
"الانتهاء، برجاء تحديث بيانات اعتماد حسابك في حال تم تغييرها وحاول مجددًا."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account (517): We are sorry, there was a technical problem "
"updating your account. Please try again."
msgstr ""
"حدثت مشكلة أثناء تحديث حسابك (517): نعتذر، حدثت مشكلة تقنية أثناء تحديث "
"حسابك. برجاء المحاولة مجددًا."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(401):We're sorry, your request timed out. Please "
"try again."
msgstr ""
"حدثت مشكلة أثناء تحديث حسابك (401): نعتذر، انتهت مهلة طلبك. برجاء المحاولة "
"مجددًا."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(403):We're sorry, there was a technical problem "
"updating your account. This kind of error is usually resolved in a few days."
" Please try again later."
msgstr ""
"حدثت مشكلة أثناء تحديث حسابك (403): نعتذر، حدثت مشكلة تقنية أثناء تحديث "
"حسابك. عادة تُحل هذه المشاكل خلال بضعة أيام. برجاء المحاولة مجددًا لاحقًا."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(404):We're sorry, there was a technical problem "
"updating your account. Please try again later."
msgstr ""
"حدثت مشكلة أثناء تحديث حسابك (404): نعتذر، حدثت مشكلة تقنية أثناء تحديث "
"حسابك. برجاء المحاولة مجددًا لاحقًا."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(409): We could not update your account because the "
"end site is experiencing technical difficulties."
msgstr ""
"حدثت مشكلة أثناء تحديث حسابك (409): تعذّر تحديث حسابك لوجود مشاكل تقنية في "
"الموقع الهدف."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(412): We could not update your account because the "
"site is experiencing technical difficulties."
msgstr ""
"حدثت مشكلة أثناء تحديث حسابك (412): تعذّر تحديث حسابك، نواجه مشاكل تقنية."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(413):We're sorry, we couldn't update your account "
"at the site because of a technical issue. This type of problem is usually "
"resolved in a few days. Please try again later."
msgstr ""
"حدثت مشكلة أثناء تحديث حسابك (413): نعتذر، تعذّر تحديث حسابك بسبب مشكلة "
"تقنية. عادة تُحل هذه المشاكل خلال بضعة أيام. برجاء المحاولة مجددًا لاحقًا."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(415): We could not update your account because the "
"site is experiencing technical difficulties."
msgstr ""
"حدثت مشكلة أثناء تحديث حسابك (415): تعذّر تحديث حسابك بسبب مشاكل تقنية."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(418): We could not update your account because the "
"site is experiencing technical difficulties. Please try later."
msgstr ""
"حدثت مشكلة أثناء تحديث حسابك (418): تعذّر تحديث حسابك بسبب مشاكل تقنية. "
"برجاء المحاولة لاحقًا."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(419):We're sorry, we couldn't update your account "
"because of unexpected variations at the site. This kind of problem is "
"usually resolved in a few days. Please try again later."
msgstr ""
"حدثت مشكلة أثناء تحديث حسابك (419): نعتذر، تعذّر تحديث حسابك لوجود تغيرات "
"مفاجئة بالموقع. عادة تُحل هذه المشاكل خلال بضعة أيام. برجاء المحاولة مجددًا "
"لاحقًا."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(425): We could not update your account because the "
"site is experiencing technical difficulties. Please try later."
msgstr ""
"حدثت مشكلة أثناء تحديث حسابك (425): تعذّر تحديث حسابك بسبب مشاكل تقنية. "
"برجاء المحاولة لاحقًا."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(426): We could not update your account for "
"technical reasons. This type of error is usually resolved in a few days. We "
"apologize for the inconvenience."
msgstr ""
"حدثت مشكلة أثناء تحديث حسابك (426): تعذّر تحديث حسابك لأسباب تقنية. عادة "
"تُحل هذه المشاكل خلال بضعة أيام. نعتذر على الإزعاج."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(507):We're sorry, Yodlee has just started providing"
" data updates for this site, and it may take a few days to be successful as "
"we get started. Please try again later."
msgstr ""
"حدثت مشكلة أثناء تحديث حسابك (507): نعتذر، لقد بدأت Yodlee حديثًا في توفير "
"تحديثات لبيانات هذا الموقع، وقد نستغرق بضعة أيام لإتمامهم بنجاح. برجاء "
"المحاولة مجددًا لاحقًا."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Property Record Not Found (510): The site is unable to find any property "
"information for your address. Please verify if the property address you have"
" provided is correct."
msgstr ""
"تعذّر العثور على سجل ملكية (510): لم يستطع الموقع العثور على أي معلومات "
"ملكية لعنوانك. برجاء التأكد من أن عنوان الملكية الذي أدرجته صحيح."

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_account_online_provider__provider_type
msgid "Provider Type"
msgstr "نوع Plaid"

#. module: account_yodlee
#: model:ir.model,name:account_yodlee.model_account_online_provider
msgid "Provider for online account synchronization"
msgstr "مزود لمزامنة الحساب"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Re-Verification Required (429): We could not update your account due to the "
"site requiring you to verify your personal information. Please log in to the"
" site and update the fields required."
msgstr ""
"مطلوب إعادة التحقق (429): تعذّر تحديث حسابك لأن الموقع يطلب أن تقوم بإعادة "
"التحقق من بياناتك الشخصية. برجاء تسجيل الدخول للموقع وتحديث الحقول المطلوبة."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Re-verification Required (427): We could not update your account due to the "
"site requiring you to view a new promotion. Please log in to the site and "
"click through to your account overview page to update the account.  We "
"apologize for the inconvenience."
msgstr ""
"مطلوب إعادة التحقق (427): تعذّر تحديث حسابك لأن الموقع يطلب أن تقوم بعرض "
"ترقية جديدة. برجاء تسجيل الدخول للموقع وفتح صفحة واجهة حسابك لتحديثه. نعتذر "
"عن الإزعاج."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Re-verification Required (428): We could not update your account due to the "
"site requiring you to accept a new Terms & Conditions. Please log in to the "
"site and read and accept the T&C."
msgstr ""
"مطلوب إعادة التحقق (428): تعذّر تحديث حسابك لأن الموقع يطلب أن تقوم "
"بالموافقة على شروط وأحكام جديدة. برجاء تسجيل الدخول للموقع وقراءة الشروط "
"والأحكام والموافقة عليها."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Registration Requires Attention (433): Auto registration is not complete. "
"Please complete your registration at the end site. Once completed, please "
"complete adding this account."
msgstr ""
"التسجيل بحاجة للتدخل (433): التسجيل التلقائي لم يكتمل. برجاء إكمال تسجيلك في"
" الموقع الهدف. ثم استكمال عملية إضافة الحساب بعد الانتهاء."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Registration Requires Attention (434): Your Auto-Registration could not be "
"completed and requires further input from you.  Please re-verify your "
"registration information to complete the process."
msgstr ""
"التسجيل بحاجة للتدخل (434): التسجيل التلقائي لم يكتمل وبحاجة لمعلومات "
"إضافية. برجاء إعادة التأكيد من بيانات تسجيلك لإكمال العملية."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Registration Requires Attention (435): Your Auto-Registration could not be "
"completed and requires further input from you.  Please re-verify your "
"registration information to complete the process."
msgstr ""
"التسجيل بحاجة للتدخل (435): التسجيل التلقائي لم يكتمل وبحاجة لمعلومات "
"إضافية. برجاء إعادة التأكيد من بيانات تسجيلك لإكمال العملية."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Request Timed Out (508): We are sorry, your request timed out due to "
"technical reasons. Please try again."
msgstr ""
"انتهت مهلة الطلب (508): نعتذر، لقد انتهت مهلة طلبك لأسباب تقنية. برجاء "
"المحاولة مجددًا."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Requested Account Type Not Found (414): We could not find your requested "
"account. You may have selected a similar site under a different category by "
"accident in which case you should select the correct site."
msgstr ""
"نوع الحساب المطلوب غير موجود (414): تعذّر إيجاد حسابك المطلوب. ربما تكون "
"اخترت بالخطأ موقعًا شبيهًا في تصنيف مختلف، في هذه الحالة عليك اختيار الموقع "
"الصحيح."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Server not reachable, please try again later"
msgstr "لا يمكننا الوصول للسيرفر، برجاء المحاولة لاحقًا"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Site Down for Maintenance(424):We were unable to update your account as the "
"site is temporarily down for maintenance. We apologize for the "
"inconvenience.  This problem is typically resolved in a few hours. Please "
"try later."
msgstr ""
"الموقع معطل للصيانة (424): تعذّر تحديث حسابك لأن الموقع معطل مؤقتًا لإجراء "
"صيانة. نعتذر على الإزعاج. هذه المشكلة تحل عادةً خلال بضعة ساعات. برجاء "
"المحاولة لاحقًا."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Site No Longer Available (411):The site no longer provides online services "
"to its customers.  Please delete this account."
msgstr ""
"لم يعد الموقع متاحًا (411): لم يعد الموقع يدعم الخدمات الإلكترونية لعملاءه. "
"برجاء حذف هذا الحساب."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Site No Longer Supported (430):This site is no longer supported for data "
"updates. Please deactivate or delete your account. We apologize for the "
"inconvenience."
msgstr ""
"لم نعد ندعم الموقع (430): لم نعد ندعم تحديث بيانات هذا الموقع. برجاء تعطيل "
"حسابك أو حذفه. نعتذر على الإزعاج."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Site Not Supported (505): We currently does not support the security system "
"used by this site. We apologize for any inconvenience. Check back "
"periodically if this situation has changed."
msgstr ""
"الموقع غير مدعوم (505): نحن لا ندعم النظام الأمني المُستخدم في هذا الموقع "
"حاليًا. نعتذر على الإزعاج. أعد تفحص الموقع دوريًا حال تغير الموقف."

#. module: account_yodlee
#: model:ir.actions.client,name:account_yodlee.yodlee_widget
msgid "Synchronization process completed"
msgstr "اكتمال عملية المزامنة"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#: code:addons/account_yodlee/models/yodlee.py:0
#: code:addons/account_yodlee/models/yodlee.py:0
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Timeout: the server did not reply within 30s"
msgstr "نفاذ الوقت: الخادم لم يرد خلال 30 ثانية"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Update Request Canceled(405):Your account was not updated because you "
"canceled the request."
msgstr "تم إلغاء طلب التحديث (405): لم يتم تحديث حسابك لأنك ألغيت الطلب."

#. module: account_yodlee
#: model:ir.model.fields.selection,name:account_yodlee.selection__account_online_provider__provider_type__yodlee
msgid "Yodlee"
msgstr "Yodlee"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_account_online_journal__yodlee_account_status
msgid "Yodlee Account Status"
msgstr "حالة حساب Yodlee"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_account_online_journal__yodlee_status_code
msgid "Yodlee Status Code"
msgstr "كود حالة Yodlee"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_res_company__yodlee_user_access_token
msgid "Yodlee access token"
msgstr "كلمة سر الوصول لـYodlee"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_res_company__yodlee_user_login
msgid "Yodlee login"
msgstr "تسجيل الدخول لـYodlee"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_res_company__yodlee_user_password
msgid "Yodlee password"
msgstr "كلمة مرور Yodlee"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_res_company__yodlee_access_token
msgid "access_token"
msgstr "access_token"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "message: %s"
msgstr "الرسالة: %s"
