# Translation of Odoo Server.
# This file contains the translation of the following modules:
# 	* account_yodlee
# 
# Translators:
# Joe Hansen <joedalton2@yahoo.dk>, 2019
# Martin Trigaux, 2019
# Pernille Kristensen <pernillekristensen1994@gmail.com>, 2019
# Sanne Kristensen <sanne@vkdata.dk>, 2019
# Ejner Sønniksen <ejner@vkdata.dk>, 2019
# lhmflexerp <lhm@flexerp.dk>, 2019
# Mads Søndergaard, 2020
# 
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server saas~12.5+e\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-08-26 08:04+0000\n"
"PO-Revision-Date: 2019-08-26 09:34+0000\n"
"Last-Translator: Mads Søndergaard, 2020\n"
"Language-Team: Danish (https://www.transifex.com/odoo/teams/41243/da/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"
"Language: da\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "(Diagnostic: %r for URL %s)"
msgstr "(Diagnostik: %r for URL %s)"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Account"
msgstr "Konto"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Account Already Registered (436):Your Auto-Registration could not be "
"completed because the site reports that your account is already registered."
"  Please log in to the site to confirm and then complete the site addition "
"process with the correct login information."
msgstr ""
"Konto allerede registreret (436): Din auto-registrering kunne ikke "
"fuldføres, fordi hjemmesiden melder, at din konto allerede er registreret. "
"Log venligst ind på hjemmesiden for at godkende og fuldføre hjemmeside "
"tillægs processen, med de korrekte login informationer."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Account Locked (407): We could not update your account because it appears "
"your account has been locked. This usually results from too many "
"unsuccessful login attempts in a short period of time. Please visit the site"
" or contact its customer support to resolve this issue.  Once done, please "
"update your account credentials in case they are changed."
msgstr ""
"Konto låst (407): Vi kunne ikke opdatere din konto, fordi det ser ud til, at"
" din konto er blevet låst. Dette er typisk et resultat af for mange ikke "
"vellykkede log ind forsøg over en kort periode. Besøg venligst hjemmesiden, "
"eller kontakt dens kundeservice, for at løse dette problem. Når det er "
"gjort, bedes du venligst opdatere dine konto informationer, i tilfælde af at"
" de er ændret."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Account Not Found(408): We're sorry, we couldn't find any accounts for you "
"at the site. Please log in at the site and confirm that your account is set "
"up, then try again."
msgstr ""
"Konto ikke fundet (408): Vi undskylder, men vi kunne ikke finde nogle konti "
"for din hjemmeside. Log venligst ind på hjemmesiden og bekræft, at din konto"
" er sat op, og forsøg igen."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Account Reported Closed (422): We were unable to update your account "
"information because it appears one or more of your related accounts have "
"been closed.  Please deactivate or delete the relevant account and try "
"again."
msgstr ""
"Konto rapporteret lukket (422): Vi kunne ikke opdatere dine konto "
"informationer, fordi det ser ud til, at en eller flere af dine relaterede "
"konti er blevet lukket. Vær venlig at deaktivere eller slette de relevante "
"konti, og prøv igen."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Account Type Not Supported(417):The type of account we found is not "
"currently supported.  Please remove this site and add as a  manual account."
msgstr ""
"Konto type ikke understøttet (417): Typen på den konto vi fandt understøttes"
" ikke i øjeblikket. Fjern venligst denne hjemmeside, og tilføj som en manuel"
" konto."

#. module: account_yodlee
#: model:ir.model.fields,help:account_yodlee.field_account_online_journal__yodlee_account_status
msgid "Active/Inactive on Yodlee system"
msgstr "Aktiver/deaktiver på Yodlee system"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "An Error has occurred (code %s)"
msgstr "Der er opstået en fejl (code %s)"

#. module: account_yodlee
#: model:ir.model,name:account_yodlee.model_res_company
msgid "Companies"
msgstr "Virksomheder"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Could not make sense of parameters: %s"
msgstr "Kunne ikke hitte ud af parametrene: %s"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Credential Re-Verification Required (402): We could not update your account "
"because your username and/or password were reported to be incorrect.  Please"
" re-verify your username and password."
msgstr ""
"Legitimationsoplysnings gen-bekræftelses påkrævet (402): Vi kunne ikke "
"opdatere din konto, eftersom dit brugernavn og/eller kodeord blev "
"rapporteret som ukorrekt. Vær venlig at bekræfte dit brugernavn og kodeord "
"igen."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Credential Re-Verification Required (420):The site has merged with another. "
"Please re-verify your credentials at the site and update the same."
msgstr ""
"Gen-bekræftelse af legitimationsoplysninger påkrævet (420): Denne hjemmeside"
" er forenet med en anden. Vær venlig at bekræfte dine "
"legitimationsoplysninger for denne hjemmeside igen, og opdater samme."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Error %s, message: %s"
msgstr "Fejl %s, besked: %s"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Error %s, message: %s, reference code: %s"
msgstr "Fejl %s, besked: %s, reference kode: %s"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Home Value Not Found (511): The site is unable to provide home value for "
"your property. We suggest you to delete this site."
msgstr ""
"Hjemmeværdi ikke fundet (511): Denne hjemmeside er ude af stand til at give "
"hjemmeværdien for din ejendom. Vi foreslår, at du sletter denne hjemmeside."

#. module: account_yodlee
#: model:ir.model,name:account_yodlee.model_account_online_journal
msgid "Interface for Online Account Journal"
msgstr "Grænseflade for netkontojournal"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Invalid Language Setting (421): The language setting for your site account "
"is not English. Please visit the site and change the language setting to "
"English."
msgstr ""
"Ugyldig sprogindstilling (421): Sprogindstillingen for din hjemmeside konto "
"er ikke Engelsk. Besøg venligst hjemmesiden og ændre sprogindstillingen til "
"Engelsk."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Additional Authentication Enrollment Required (521) : Please "
"enroll in the new security authentication system, <Account Name> has "
"introduced. Ensure your account settings in <Cobrand> are updated with this "
"information."
msgstr ""
"MFA fejl: Yderligere godkendelsesregistrering påkrævet (521) : Registrer dig"
" venligst i det nye sikkerheds godkendelses system, som <Account Name> har "
"introduceret. Tjek at dine kontoindstillinger i <Cobrand> er opdaterede med "
"denne information."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Authentication Information Expired (524):We're sorry, the "
"authentication information you provided has expired. Please try again."
msgstr ""
"MFA fejl: Godkendelsesinformation udløbet (524): Vi er kede af det, men "
"godkendelsesinformationen du angav er udløbet. Prøv venligst igen."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Authentication Information Incorrect (520):We're sorry, the site "
"indicates that the additional authentication information you provided is "
"incorrect. Please try updating your account again."
msgstr ""
"MFA fejl: Ukorrekt godkendelsesinformation (520): Vi er kede af det, men "
"hjemmesiden indikere at de ekstra godkendelsesinformationer du angiv, er "
"ukorrekte. Prøv venligst at opdatere din konto igen."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Authentication Information Incorrect (523):We're sorry, the "
"authentication information you  provided is incorrect. Please try again."
msgstr ""
"MFA fejl: Ukorrekt godkendelsesinformation (523): Vi er kede af det, men "
"godkendelsesinformationerne du angav, er ukorrekte. Prøv venligst igen."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Authentication Information Required (519): Your account was not "
"updated as your authentication information like security question and answer"
" was unavailable or incomplete. Please update your account settings."
msgstr ""
"MFA fejl: Godkendelsesinformation er påkrævet (519): Din konto blev ikke "
"opdateret, eftersom din godkendelsesinformation så som sikkerhedsspørgsmål "
"og svar, var utilgængelige er ufuldstændige. Vær venlig at opdatere dine "
"kontoindstillinger."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Authentication Information Unavailable (518):Your account was not"
" updated as the required additional authentication information was "
"unavailable. Please try now."
msgstr ""
"MFA fejl: Utilgængelig godkendelsesinformation 8518): Din konto blev ikke "
"opdateret eftersom de påkrævede ekstra godkendelsesinformationer var "
"utilgængelige. Prøv venligst nu."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Credential Re-Verification Required (526): We could not update "
"your account because your username/password or additional security "
"credentials are incorrect. Please try again."
msgstr ""
"MFA fejl: Gen-godkendelse af legitimationsoplysning påkrævet (526): Vi kunne"
" ikke opdatere din konto, eftersom dit brugernavn/kodeord, eller ekstra "
"sikkerhedsinformationer, er ukorrekte. Prøv venligst igen."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Problem Updating Account (525): We could not update your account "
"for technical reasons. This type of error is usually resolved in a few days."
" We apologize for the inconvenience. Please try again later."
msgstr ""
"MFA fejl: Problem ved opdatering af konto (525): Vi kunne ikke opdatere din "
"konto på grund af tekniske vanskeligheder. Denne type fejl løses typisk "
"efter et par dage. Vi undskylder ulejligheden. Prøv venligst igen senere."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Request Timed Out (522) :Your request has timed out as the "
"required security information was unavailable or was not provided within the"
" expected time. Please try again."
msgstr ""
"MFA fejl: Forespørgsel udløb (522): Din forespørgsel udløb eftersom den "
"påkrævede sikkerhedsinformation var utilgængelig, eller ikke blev delt "
"indenfor den forventede tidsramme. Prøv venligst igen."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Site Device Information Expired(509): We're sorry, we can't "
"update your account because your token is no longer valid at the site. "
"Please update your information and try again, or contact customer support."
msgstr ""
"MFA fejl: Hjemmeside enhed information udløbet (509): Vi undskylder, men vi "
"kan ikke opdatere din konto, eftersom din token ikke længere er gyldig for "
"denne hjemmeside. Opdater venligst dine informationer og prøv igen, eller "
"kontakt kundeservice."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Multiple User Logins(416): We attempted to update your account, but another "
"session was already established at the same time.  If you are currently "
"logged on to this account directly, please log off and try after some time"
msgstr ""
"Adskillige brugelogins (416): Vi forsøgte at opdatere din konto, men en "
"anden session var allerede oprettet på samme tid. Hvis du i øjeblikket er "
"logget ind på denne konto direkte, bedes du venligst logge ud, og prøve "
"efter noget tid."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"New Login Information Required(506):We're sorry, to log in to this site, you"
" need to provide additional information. Please update your account and try "
"again."
msgstr ""
"Ny login information påkrævet (506): Vi er kede af det, men for at logge ind"
" på denne hjemmeside, skal du angive yderligere informationer. Opdater "
"venligst din konto, og forsøg igen."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"No Account Found (423): We were unable to detect an account. Please verify "
"that you account information is available at this time and If the problem "
"persists, please contact customer support at online@odoo.com for further "
"assistance."
msgstr ""
"Ingen konto fundet (423): Vi kunne ikke finde en konto. Bekræft venligst at "
"dine konto informationer er tilgængelige i øjeblikket, og hvis problemet "
"fortsætter, så kontakt venligst kundeservice på online@odoo.com for "
"yderligere hjælp."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"No Payees Found(512):Your request cannot be completed as no payees were "
"found in your account."
msgstr ""
"Ingen betalende fundet (512): Din anmodning kunne ikke fuldføres eftersom "
"ingen betalende blev fundet i din konto."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Online institution"
msgstr "Online institution"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Please configure an email in the company settings."
msgstr "Vær venlig at konfigurere en email i virksomhedsindstillinger."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account (406): We could not update your account because the"
" site requires you to perform some additional action. Please visit the site "
"or contact its customer support to resolve this issue. Once done, please "
"update your account credentials in case they are changed else try again."
msgstr ""
"Problem med opdatering af konto (406): Vi kunne ikke opdatere din konto, "
"eftersom hjemmesiden kræver, at du udfører visse yderligere handlinger. Vær "
"venlig at besøge eller kontakte dets kundeservice for at løse dette problem."
" Når det er gjort, bedes du venligst opdatere din kontos "
"legitimationsoplysninger, i tilfælde af at de er blevet ændret, ellers prøv "
"igen."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account (517): We are sorry, there was a technical problem "
"updating your account. Please try again."
msgstr ""
"Problem med opdatering af konto (517): Vi er kede af det, men der var et "
"teknisk problem med opdateringen af din konto. Prøv venligst igen."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(401):We're sorry, your request timed out. Please "
"try again."
msgstr ""
"Problem med opdatering af konto (401): Vi er kede af det, men din anmodning "
"udløb. Prøv venligst igen."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(403):We're sorry, there was a technical problem "
"updating your account. This kind of error is usually resolved in a few days."
" Please try again later."
msgstr ""
"Problem med opdatering af konto (403): Vi er kede af det, men der var et "
"teknisk problem med opdateringen af din konto. Denne type fejl er typisk "
"løst indenfor et par dage. Prøv venligst igen senere."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(404):We're sorry, there was a technical problem "
"updating your account. Please try again later."
msgstr ""
"Problem med opdatering af konto (404): Vi er kede af det, men der var et "
"teknisk problem med opdateringen af din konto. Prøv venligst igen senere."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(409): We could not update your account because the "
"end site is experiencing technical difficulties."
msgstr ""
"Problem med opdatering af konto (409): Vi kunne ikke opdatere din konto, "
"eftersom destinations hjemmesiden i øjeblikket har tekniske udfordringer."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(412): We could not update your account because the "
"site is experiencing technical difficulties."
msgstr ""
"Problem med opdatering af konto (412): Vi kunne ikke opdatere din konto, "
"eftersom hjemmesiden i øjeblikket har tekniske udfordringer."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(413):We're sorry, we couldn't update your account "
"at the site because of a technical issue. This type of problem is usually "
"resolved in a few days. Please try again later."
msgstr ""
"Problem med opdatering af konto (413): Vi er kede af det, men vi kunne ikke "
"opdatere din konto på hjemmesiden, grundet tekniske udfordringer. Dette type"
" problem er oftest løst indenfor et par dage. Prøv venligst igen senere."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(415): We could not update your account because the "
"site is experiencing technical difficulties."
msgstr ""
"Problem med opdatering af konto (415): Vi kunne ikke opdatere din konto, "
"fordi hjemmesiden i øjeblikket har tekniske udfordringer."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(418): We could not update your account because the "
"site is experiencing technical difficulties. Please try later."
msgstr ""
"Problem med opdatering af konto (418): Vi kunne ikke opdatere din konto, "
"fordi hjemmesiden i øjeblikket har tekniske udfordringer. Prøv venligst igen"
" senere."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(419):We're sorry, we couldn't update your account "
"because of unexpected variations at the site. This kind of problem is "
"usually resolved in a few days. Please try again later."
msgstr ""
"Problem med opdatering af konto (419): Vi er kede af det, men vi kunne ikke "
"opdatere din konto, grundet uforudsete variationer på hjemmesiden. Dette "
"type problem er oftest løst indenfor et par dage. Prøv venligst igen senere."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(425): We could not update your account because the "
"site is experiencing technical difficulties. Please try later."
msgstr ""
"Problem med opdatering af konto (425): Vi kunne ikke opdatere din konto, "
"fordi hjemmesiden i øjeblikket har tekniske udfordringer. Prøv venligst igen"
" senere."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(426): We could not update your account for "
"technical reasons. This type of error is usually resolved in a few days. We "
"apologize for the inconvenience."
msgstr ""
"Problem med opdatering af konto (426): Vi kunne ikke opdatere din konto af "
"tekniske årsager. Dette type problem er typisk løst indenfor et par dage. Vi"
" beklager ulejligheden."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(507):We're sorry, Yodlee has just started providing"
" data updates for this site, and it may take a few days to be successful as "
"we get started. Please try again later."
msgstr ""
"Problem med opdatering af konto (507): Vi er kede af det, men Yodlee har "
"just påbegyndt data opdateringer for denne hjemmeside, og det kan tage et "
"par dage før det lykkes, imens vi får startet. Prøv venligst igen senere."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Property Record Not Found (510): The site is unable to find any property "
"information for your address. Please verify if the property address you have"
" provided is correct."
msgstr ""
"Ejendomsregistrering ikke fundet (510): Hjemmesiden kunne ikke finde nogen "
"ejendomsinformation for din adresse. Bekræft venligst, at de "
"ejendomsinformationer du har angivet, er korrekte."

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_account_online_provider__provider_type
msgid "Provider Type"
msgstr "Leverandørtype"

#. module: account_yodlee
#: model:ir.model,name:account_yodlee.model_account_online_provider
msgid "Provider for online account synchronization"
msgstr "Leverandør af online kontosynkronisering"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Re-Verification Required (429): We could not update your account due to the "
"site requiring you to verify your personal information. Please log in to the"
" site and update the fields required."
msgstr ""
"Gen-bekræftelse påkrævet (429): Vi kunne ikke opdatere din konto eftersom "
"hjemmesiden kræver at du bekræfter dine personlige informationer. Log "
"venligst ind på hjemmesiden og opdater de påkrævede felter."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Re-verification Required (427): We could not update your account due to the "
"site requiring you to view a new promotion. Please log in to the site and "
"click through to your account overview page to update the account.  We "
"apologize for the inconvenience."
msgstr ""
"Gen-bekræftelse påkrævet (427): Vi kunne ikke opdatere din konto, eftersom "
"hjemmesiden kræver, at du ser en ny kampagne. Log venligst ind på "
"hjemmesiden og klik gennem din kontooversigts side, for at opdatere kontoen."
" Vi beklager ulejligheden."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Re-verification Required (428): We could not update your account due to the "
"site requiring you to accept a new Terms & Conditions. Please log in to the "
"site and read and accept the T&C."
msgstr ""
"Gen-bekræftelse påkrævet (428): Vi kunne ikke opdatere din konto eftersom "
"hjemmesiden kræver, at du acceptere nye Vilkår & Betingelser. Log venligst "
"ind på hjemmesiden, læs, og accepter disse."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Registration Requires Attention (433): Auto registration is not complete. "
"Please complete your registration at the end site. Once completed, please "
"complete adding this account."
msgstr ""
"Registrering kræver opmærksomhed (433): Auto-registrering er ikke fuldført. "
"Vær venlig at fuldføre din registrering på destinations hjemmesiden. Når det"
" er fuldført, bedes du færdiggøre tilføjelsen af denne konto."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Registration Requires Attention (434): Your Auto-Registration could not be "
"completed and requires further input from you.  Please re-verify your "
"registration information to complete the process."
msgstr ""
"Registrering kræver opmærksomhed (434): Din auto-registrering kunne ikke "
"fuldføres, og kræver yderligere informationer fra dig. Vær venlig at gen-"
"verificere dine registrerings informationer, for at fuldføre processen."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Registration Requires Attention (435): Your Auto-Registration could not be "
"completed and requires further input from you.  Please re-verify your "
"registration information to complete the process."
msgstr ""
"Registrering kræver opmærksomhed (435): Din auto-registrering kunne ikke "
"fuldføres, og kræver yderligere informationer fra dig. Vær venlig at gen-"
"verificere dine registrerings informationer, for at fuldføre processen."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Request Timed Out (508): We are sorry, your request timed out due to "
"technical reasons. Please try again."
msgstr ""
"Forespørgsel udløb (508): Vi er kede af det, men din forespørgsel udløb, "
"grundet tekniske årsager. Prøv venligst igen."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Requested Account Type Not Found (414): We could not find your requested "
"account. You may have selected a similar site under a different category by "
"accident in which case you should select the correct site."
msgstr ""
"Anmodet kontotype findes ikke (414): Vi kunne ikke finde kontoen du anmodede"
" om. Du kan, ved en fejl, have valgt en lignende hjemmesider under en anden "
"kategori, i hvilket tilfælde du burde vælge den korrekte hjemmeside."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Server not reachable, please try again later"
msgstr "Serveren kunne ikke nås, prøv venligst igen senere"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Site Down for Maintenance(424):We were unable to update your account as the "
"site is temporarily down for maintenance. We apologize for the "
"inconvenience.  This problem is typically resolved in a few hours. Please "
"try later."
msgstr ""
"Side nede for vedligeholdelse (424): Vi var ude af stand til at opdatere din"
" konto, eftersom hjemmesiden midlertidigt er nede for vedligeholdelse. Vi "
"beklager ulejligheden. Dette problem er typisk løst indenfor et par timer. "
"Prøv venligst igen senere."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Site No Longer Available (411):The site no longer provides online services "
"to its customers.  Please delete this account."
msgstr ""
"Siden er ikke længere tilgængelig (411): Siden tilbyder ikke længere online "
"services til sine kunder. Slet venligst denne konto."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Site No Longer Supported (430):This site is no longer supported for data "
"updates. Please deactivate or delete your account. We apologize for the "
"inconvenience."
msgstr ""
"Hjemmeside ikke længere understøttet (430): Denne hjemmeside understøttes "
"ikke længere i forhold til data opdateringer. Vær venlig at deaktivere eller"
" slette din konto. Vi beklager ulejligheden."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Site Not Supported (505): We currently does not support the security system "
"used by this site. We apologize for any inconvenience. Check back "
"periodically if this situation has changed."
msgstr ""
"Hjemmeside ikke understøttet (505): Vi understøtter i øjeblikket ikke "
"sikkerhedssystemet som anvendes af hjemmesiden. Vi beklager ulejligheden. "
"Kom tilbage i ny og næ, og se om situationen har ændret sig."

#. module: account_yodlee
#: model:ir.actions.client,name:account_yodlee.yodlee_widget
msgid "Synchronization process completed"
msgstr "Synkroniserings proces fuldført"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#: code:addons/account_yodlee/models/yodlee.py:0
#: code:addons/account_yodlee/models/yodlee.py:0
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Timeout: the server did not reply within 30s"
msgstr "Timeout: serveren svarede ikke inden for 30s"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Update Request Canceled(405):Your account was not updated because you "
"canceled the request."
msgstr ""
"Opdateringsanmodning annulleret (405): Din konto blev ikke opdateret, fordi "
"du annullerede anmodningen."

#. module: account_yodlee
#: model:ir.model.fields.selection,name:account_yodlee.selection__account_online_provider__provider_type__yodlee
msgid "Yodlee"
msgstr "Yodlee"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_account_online_journal__yodlee_account_status
msgid "Yodlee Account Status"
msgstr "Yodlee kontostatus"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_account_online_journal__yodlee_status_code
msgid "Yodlee Status Code"
msgstr "Yodlee Statuskode"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_res_company__yodlee_user_access_token
msgid "Yodlee access token"
msgstr "Yodlee adgangs token"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_res_company__yodlee_user_login
msgid "Yodlee login"
msgstr "Todlee login"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_res_company__yodlee_user_password
msgid "Yodlee password"
msgstr "Yodlee kodeord"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_res_company__yodlee_access_token
msgid "access_token"
msgstr "access_token"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "message: %s"
msgstr "besked: %s"
