# Translation of Odoo Server.
# This file contains the translation of the following modules:
# 	* account_yodlee
# 
# Translators:
# Martin Trigaux, 2019
# Eloïse Stilmant <est@odoo.com>, 2019
# Pauline Thiry <pth@odoo.com>, 2020
# Cécile Collart <cco@odoo.com>, 2020
# 
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server saas~12.5+e\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-08-26 08:04+0000\n"
"PO-Revision-Date: 2019-08-26 09:34+0000\n"
"Last-Translator: Cécile Collart <cco@odoo.com>, 2020\n"
"Language-Team: French (https://www.transifex.com/odoo/teams/41243/fr/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"
"Language: fr\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "(Diagnostic: %r for URL %s)"
msgstr "(Diagnostique : %r à l'adresse %s)"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Account"
msgstr "Compte"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Account Already Registered (436):Your Auto-Registration could not be "
"completed because the site reports that your account is already registered."
"  Please log in to the site to confirm and then complete the site addition "
"process with the correct login information."
msgstr ""
"Compte déjà enregistré (436): la création de compte automatique a échouée "
"car votre compte est déjà enregistré sur ce site. Connectez-vous sur ce site"
" et corrigé l'ajout de site avec les informations de connexion correctes."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Account Locked (407): We could not update your account because it appears "
"your account has been locked. This usually results from too many "
"unsuccessful login attempts in a short period of time. Please visit the site"
" or contact its customer support to resolve this issue.  Once done, please "
"update your account credentials in case they are changed."
msgstr ""
"Compte verrouillé (407) : nous n'avons pas pu mettre à jour les informations"
" de votre compte car il est verrouillé. Il s'agit généralement de la "
"conséquence d'un trop grand nombre de tentatives d'identification sur une "
"courte période. Veuillez vous rendre sur le site ou contacter le support "
"utilisateur pour résoudre le problème. Une fois le problème résolu, "
"n'oubliez pas de mettre à jour vos informations de connexion si elles ont "
"changé."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Account Not Found(408): We're sorry, we couldn't find any accounts for you "
"at the site. Please log in at the site and confirm that your account is set "
"up, then try again."
msgstr ""
"Compte non trouvé(408): nous sommes désolés, nous n’avons pas pu retrouver "
"votre compte sur le site. Veuillez vous connecter au site et confirmer que "
"votre compte est configuré, puis réessayez."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Account Reported Closed (422): We were unable to update your account "
"information because it appears one or more of your related accounts have "
"been closed.  Please deactivate or delete the relevant account and try "
"again."
msgstr ""
"Compte clôturé (422): nous n’avons pas pu mettre les informations de votre "
"compte à jour, car il semblerait qu’un ou plusieurs de vos comptes aient été"
" clôturés. Veuillez désactiver ou supprimer le ou les comptes correspondants"
" et réessayez."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Account Type Not Supported(417):The type of account we found is not "
"currently supported.  Please remove this site and add as a  manual account."
msgstr ""
"Type de compte non pris en charge(417): le type de compte que nous avons "
"trouvé n’est actuellement pas pris en charge. Veuillez supprimer ce site et "
"ajoutez-le en tant que compte manuel."

#. module: account_yodlee
#: model:ir.model.fields,help:account_yodlee.field_account_online_journal__yodlee_account_status
msgid "Active/Inactive on Yodlee system"
msgstr "Actif/inactif sur Yodlee "

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "An Error has occurred (code %s)"
msgstr "Une erreur est survenue (code %s)"

#. module: account_yodlee
#: model:ir.model,name:account_yodlee.model_res_company
msgid "Companies"
msgstr "Sociétés"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Could not make sense of parameters: %s"
msgstr "Impossible de donner un sens aux paramètres : %s"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Credential Re-Verification Required (402): We could not update your account "
"because your username and/or password were reported to be incorrect.  Please"
" re-verify your username and password."
msgstr ""
"Revérification des identifiants obligatoire (402): Nous ne pouvons pas "
"mettre à jour votre compte car votre compte et/ou mot de passe ont été "
"rapporté comme incorrects. Merci de revérifier votre compte et mot de passe."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Credential Re-Verification Required (420):The site has merged with another. "
"Please re-verify your credentials at the site and update the same."
msgstr ""
"Revérification des identifiants obligatoire (420) : le site a fusionné avec "
"un autre. Merci de revérifier vos identifiants sur le site et de les mettre "
"à jour."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Error %s, message: %s"
msgstr "Erreur %s, message: %s"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Error %s, message: %s, reference code: %s"
msgstr "Erreur %s, message: %s, code de réference: %s"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Home Value Not Found (511): The site is unable to provide home value for "
"your property. We suggest you to delete this site."
msgstr ""
"Valeur du logement introuvable (511) : le site ne peut pas fournir de valeur"
" pour votre propriété. Nous vous suggérons de supprimer ce site."

#. module: account_yodlee
#: model:ir.model,name:account_yodlee.model_account_online_journal
msgid "Interface for Online Account Journal"
msgstr "Interface pour le Journal des Comptes en Ligne"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Invalid Language Setting (421): The language setting for your site account "
"is not English. Please visit the site and change the language setting to "
"English."
msgstr ""
"Paramètre de langue non valide (421) : Votre compte de site n'est pas "
"paramétré en français. Consultez le site et remplacez le paramètre de langue"
" par le français."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Additional Authentication Enrollment Required (521) : Please "
"enroll in the new security authentication system, <Account Name> has "
"introduced. Ensure your account settings in <Cobrand> are updated with this "
"information."
msgstr ""
"Erreur MFA : Inscription à une authentification supplémentaire requise (521)"
" : Veuillez vous inscrire au nouveau système d'authentification de sécurité "
"que <Account Name> a mis en place. Veillez à ce que les paramètres de votre "
"compte sur <Cobrand> soient mis à jour avec ces informations."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Authentication Information Expired (524):We're sorry, the "
"authentication information you provided has expired. Please try again."
msgstr ""
"Erreur MF : Informations d'authentification expirées (524) : Nous sommes "
"désolés, les informations d'authentification que vous avez fournies ont "
"expiré. Veuillez réessayer."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Authentication Information Incorrect (520):We're sorry, the site "
"indicates that the additional authentication information you provided is "
"incorrect. Please try updating your account again."
msgstr ""
"Erreur MFA : Informations d’authentification incorrectes (520) : Nous sommes"
" désolés, d’après le site, les informations d’authentification "
"supplémentaire que vous avez fournies sont incorrectes. Veuillez remettre "
"votre compte à jour."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Authentication Information Incorrect (523):We're sorry, the "
"authentication information you  provided is incorrect. Please try again."
msgstr ""
"Erreur MF : Informations d’authentification incorrectes (523) : Nous sommes "
"désolés, les informations d’authentification que vous avez fournies sont "
"incorrectes. Veuillez réessayer."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Authentication Information Required (519): Your account was not "
"updated as your authentication information like security question and answer"
" was unavailable or incomplete. Please update your account settings."
msgstr ""
"Erreur MFA : Informations d’authentification requises (519) : Votre compte "
"n’a pas été mis à jour, dans la mesure où les informations "
"d’authentification telles que la question et réponse de sécurité étaient "
"indisponibles ou incomplètes. Veuillez mettre à jour les paramètres de votre"
" compte."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Authentication Information Unavailable (518):Your account was not"
" updated as the required additional authentication information was "
"unavailable. Please try now."
msgstr ""
"Erreur MFA : Informations d’authentification non disponibles (518) : Votre "
"compte n’a pas été mis à jour, dans la mesure où les informations "
"d’authentification supplémentaire n’étaient pas disponibles. Veuillez "
"essayer maintenant."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Credential Re-Verification Required (526): We could not update "
"your account because your username/password or additional security "
"credentials are incorrect. Please try again."
msgstr ""
"Erreur MFA : Revérification des identifiants obligatoire (526) : Nous "
"n’avons pas pu mettre votre compte à jour, car votre nom d’utilisateur/mot "
"de passe ou vos informations d’identification supplémentaire de sécurité "
"sont incorrects. Veuillez réessayer."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Problem Updating Account (525): We could not update your account "
"for technical reasons. This type of error is usually resolved in a few days."
" We apologize for the inconvenience. Please try again later."
msgstr ""
"Erreur MF : Problème lors de la mise à jour du compte (525) : Pour des "
"raisons techniques, nous n’avons pas pu mettre votre compte à jour. Ce type "
"d’erreur est généralement résolu en quelques jours. Nous vous prions de nous"
" excuser pour ces inconvénients. Veuillez réessayer ultérieurement."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Request Timed Out (522) :Your request has timed out as the "
"required security information was unavailable or was not provided within the"
" expected time. Please try again."
msgstr ""
"Erreur MFA : Délai dépassé pour la demande (522) : Votre demande a dépassé "
"le délai d’expiration, car les informations de sécurité requises étaient "
"indisponibles ou non fournies dans les délais prévus. Veuillez réessayer."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Site Device Information Expired(509): We're sorry, we can't "
"update your account because your token is no longer valid at the site. "
"Please update your information and try again, or contact customer support."
msgstr ""
"Erreur MFA : Informations sur l’appareil du site arrivées à expiration(509) "
": Nous sommes désolés, nous ne pouvons pas mettre à jour votre compte, car "
"votre jeton n’est plus valide sur le site. Veuillez mettre vos informations "
"à jour avant de réessayer ou contactez le support client."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Multiple User Logins(416): We attempted to update your account, but another "
"session was already established at the same time.  If you are currently "
"logged on to this account directly, please log off and try after some time"
msgstr ""
"Connexions de plusieurs utilisateurs (416) : Nous avons essayé de mettre "
"votgre compte à jour, mais une autre session était ouverte au même moment. "
"Si vous êtes actuellement connecté à ce compte, veuillez vous déconnecter et"
" réessayer après un certain temps."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"New Login Information Required(506):We're sorry, to log in to this site, you"
" need to provide additional information. Please update your account and try "
"again."
msgstr ""
"Nouvelles informations de connexion requises(506) : Nous sommes désolés. "
"Pour vous connecter à ce site, vous devez fournir des informations "
"supplémentaires. Veuillez mettre à jour votre compte avant de réessayer."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"No Account Found (423): We were unable to detect an account. Please verify "
"that you account information is available at this time and If the problem "
"persists, please contact customer support at online@odoo.com for further "
"assistance."
msgstr ""
"Compte introuvable (423) : Nous n’avons pas pu détecter de compte. Vérifiez "
"que les informations de votre compte sont disponibles à ce stade, et si le "
"problème persiste, contactez le support client à l’adresse online@odoo.com "
"pour plus d’assistance."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"No Payees Found(512):Your request cannot be completed as no payees were "
"found in your account."
msgstr ""
"Bénéficiaires introuvables (512) : Impossible de répondre à votre demande, "
"car aucun bénéficiaire n’a été trouvé sur votre compte."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Online institution"
msgstr "Institution en ligne"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Please configure an email in the company settings."
msgstr "Configurez un email dans la configuration de la société"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account (406): We could not update your account because the"
" site requires you to perform some additional action. Please visit the site "
"or contact its customer support to resolve this issue. Once done, please "
"update your account credentials in case they are changed else try again."
msgstr ""
"Problème lors de la mise à jour du compte (406) : Impossible de mettre votre"
" compte à jour, car le site nécessite une intervention supplémentaire de "
"votre part. Veuillez vous rendre sur le site ou contacter le support "
"clientèle pour la résolution de ce problème. Une fois le problème résolu, "
"mettez à jour vos informations de connexion si elles ont changé ou "
"réessayez."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account (517): We are sorry, there was a technical problem "
"updating your account. Please try again."
msgstr ""
"Problème lors de la mise à jour du compte (517): Nous sommes désolés, un "
"problème technique est survenu. Veuillez réessayer."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(401):We're sorry, your request timed out. Please "
"try again."
msgstr ""
"Problème lors de la mise à jour du compte (401) : Nous sommes désolés, le "
"délai d'attente de votre demande a été dépassé. Veuillez réessayer."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(403):We're sorry, there was a technical problem "
"updating your account. This kind of error is usually resolved in a few days."
" Please try again later."
msgstr ""
"Problème lors de la mise à jour du compte (403) : Nous sommes désolés, un "
"problème technique s'est produit lors de la mise à jour de votre compte. Ce "
"type d’erreur est généralement résolu en quelques jours. Réessayez "
"ultérieurement."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(404):We're sorry, there was a technical problem "
"updating your account. Please try again later."
msgstr ""
"Problème lors de la mise à jour du compte (404) : Nous sommes désolés. Un "
"problème technique est survenu lors de la mise à jour de votre compte. "
"Veuillez réessayer ultérieurement."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(409): We could not update your account because the "
"end site is experiencing technical difficulties."
msgstr ""
"Problème lors de la mise à jour du compte (409) : Nous n'avons pas pu mettre"
" votre compte à jour, car le site final éprouve actuellement des difficultés"
" techniques."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(412): We could not update your account because the "
"site is experiencing technical difficulties."
msgstr ""
"Problème lors de la mise à jour du compte (412) : Nous n'avons pas pu mettre"
" votre compte à jour, car le site éprouve actuellement des difficultés "
"techniques."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(413):We're sorry, we couldn't update your account "
"at the site because of a technical issue. This type of problem is usually "
"resolved in a few days. Please try again later."
msgstr ""
"Problème lors de la mise à jour du compte (413) : Pour des raisons "
"techniques, nous n’avons pas pu mettre votre compte à jour. Ce type de "
"problème est généralement résolu en quelques jours. Réessayez "
"ultérieurement."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(415): We could not update your account because the "
"site is experiencing technical difficulties."
msgstr ""
"Problème lors de la mise à jour du compte (415) : Nous n'avons pas pu mettre"
" votre compte à jour, car le site éprouve actuellement des difficultés "
"techniques."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(418): We could not update your account because the "
"site is experiencing technical difficulties. Please try later."
msgstr ""
"Problème lors de la mise à jour du compte (418) : Nous n'avons pas pu mettre"
" votre compte à jour, car le site éprouve actuellement des difficultés "
"techniques. Réessayez ultérieurement."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(419):We're sorry, we couldn't update your account "
"because of unexpected variations at the site. This kind of problem is "
"usually resolved in a few days. Please try again later."
msgstr ""
"Problème lors de la mise à jour du compte (419) : Pour des variations "
"inattendues sur le site, nous n’avons pas pu mettre votre compte à jour. Ce "
"type de problème est généralement résolu en quelques jours. Veuillez "
"réessayer ultérieurement."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(425): We could not update your account because the "
"site is experiencing technical difficulties. Please try later."
msgstr ""
"Problème lors de la mise à jour du compte (427) : Nous n'avons pas pu mettre"
" votre compte à jour, car le site éprouve actuellement des difficultés "
"techniques. Veuillez réessayer ultérieurement."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(426): We could not update your account for "
"technical reasons. This type of error is usually resolved in a few days. We "
"apologize for the inconvenience."
msgstr ""
"Problème lors de la mise à jour du compte (426) : Pour des raisons "
"techniques, nous n’avons pas pu mettre votre compte à jour. Ce type d’erreur"
" est généralement résolu en quelques jours. Nous vous prions de nous excuser"
" pour ces inconvénients."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(507):We're sorry, Yodlee has just started providing"
" data updates for this site, and it may take a few days to be successful as "
"we get started. Please try again later."
msgstr ""
"Problème lors de la mise à jour du compte (507) : Nous sommes désolés, "
"Yodlee commence tout juste à fournir des mises à jour de données pour ce "
"site et cela peut prendre plusieurs jours. Veuillez réessayer "
"ultérieurement."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Property Record Not Found (510): The site is unable to find any property "
"information for your address. Please verify if the property address you have"
" provided is correct."
msgstr ""
"Enregistrement de la propriété introuvable (510) : Le site ne peut trouver "
"aucune information sur la propriété pour votre adresse. Veuillez vérifier "
"l'exactitude de l'adresse que vous avez fournie pour la propriété."

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_account_online_provider__provider_type
msgid "Provider Type"
msgstr "Type de fournisseur"

#. module: account_yodlee
#: model:ir.model,name:account_yodlee.model_account_online_provider
msgid "Provider for online account synchronization"
msgstr "Fournisseur de synchronisation de banque en ligne"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Re-Verification Required (429): We could not update your account due to the "
"site requiring you to verify your personal information. Please log in to the"
" site and update the fields required."
msgstr ""
"Revérification obligatoire (429): nous ne pouvons pas mettre à jour votre "
"compte, car le site vous demande de vérifier vos informations personnelles. "
"Connectez-vous sur ce site et mettez à jour les champs requis."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Re-verification Required (427): We could not update your account due to the "
"site requiring you to view a new promotion. Please log in to the site and "
"click through to your account overview page to update the account.  We "
"apologize for the inconvenience."
msgstr ""
"Revérification obligatoire (427): nous ne pouvons pas mettre à jour votre "
"compte, car le site vous demande de voir une nouvelle promotion. Connectez-"
"vous sur ce site et cliquez sur la page de présentation de votre compte pour"
" le mettre à jour. Nous nous excusons pour les inconvénients."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Re-verification Required (428): We could not update your account due to the "
"site requiring you to accept a new Terms & Conditions. Please log in to the "
"site and read and accept the T&C."
msgstr ""
"Revérification obligatoire (428): nous ne pouvons pas mettre à jour votre "
"compte, car le site vous demande d’accepter les nouvelles Conditions "
"générales. Connectez-vous sur ce site, et lisez et acceptez les Conditions "
"générales."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Registration Requires Attention (433): Auto registration is not complete. "
"Please complete your registration at the end site. Once completed, please "
"complete adding this account."
msgstr ""
"L’inscription nécessite votre attention (433): l’inscription automatique "
"n'est pas terminée. Veuillez compléter votre inscription sur le site final. "
"Une fois terminée, terminez l’ajout de ce compte."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Registration Requires Attention (434): Your Auto-Registration could not be "
"completed and requires further input from you.  Please re-verify your "
"registration information to complete the process."
msgstr ""
"L’inscription nécessite votre attention (434): votre inscription automatique"
" ne peut pas être terminée, il faut que vous interveniez . Veuillez "
"revérifier vos informations d’inscription pour terminer le processus."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Registration Requires Attention (435): Your Auto-Registration could not be "
"completed and requires further input from you.  Please re-verify your "
"registration information to complete the process."
msgstr ""
"L’inscription nécessite votre attention (435): votre inscription automatique"
" ne peut pas être terminée, il faut que vous interveniez . Veuillez "
"revérifier vos informations d’inscription pour terminer le processus."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Request Timed Out (508): We are sorry, your request timed out due to "
"technical reasons. Please try again."
msgstr ""
"Délai d’attente de la requête dépassé (508): nous sommes désolés, le délai "
"d’attente de votre requête a été dépassé pour des raisons techniques. "
"Veuillez réessayer."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Requested Account Type Not Found (414): We could not find your requested "
"account. You may have selected a similar site under a different category by "
"accident in which case you should select the correct site."
msgstr ""
"Type de compte demandé introuvable (414): nous n’avons pas trouvé le compte "
"que vous avez demandé. Vous avez peut-être sélectionné un site similaire "
"dans une catégorie différente par erreur, auquel cas vous devez sélectionner"
" le bon site."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Server not reachable, please try again later"
msgstr "Serveur inaccessible, merci de réessayer plus tard"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Site Down for Maintenance(424):We were unable to update your account as the "
"site is temporarily down for maintenance. We apologize for the "
"inconvenience.  This problem is typically resolved in a few hours. Please "
"try later."
msgstr ""
"Site indisponible pour cause de maintenance (424): nous n’avons pas pu "
"mettre à jour votre compte, car le site est temporairement indisponible pour"
" cause de maintenance. Nous vous prions de nous excuser pour ces "
"inconvénients. Ce problème est généralement résolu en quelques heures. Merci"
" de réessayer plus tard."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Site No Longer Available (411):The site no longer provides online services "
"to its customers.  Please delete this account."
msgstr ""
"Site plus disponible (411): le site ne fournit plus de services en ligne à "
"ses clients. Veuillez supprimer ce compte."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Site No Longer Supported (430):This site is no longer supported for data "
"updates. Please deactivate or delete your account. We apologize for the "
"inconvenience."
msgstr ""
"Site plus pris en charge (430): ce site n’est plus pris en charge pour les "
"mises à jour de données. Veuillez désactiver ou supprimer votre compte.  "
"Nous vous prions de nous excuser pour ces inconvénients."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Site Not Supported (505): We currently does not support the security system "
"used by this site. We apologize for any inconvenience. Check back "
"periodically if this situation has changed."
msgstr ""
"Site non supporté (505): Nous ne supportons pas le système de sécurité "
"utilisé par ce site web pour le moment. Nous nous excusons pour tout "
"inconvénient. Revenez voir de temps en temps si la situation a changé. "

#. module: account_yodlee
#: model:ir.actions.client,name:account_yodlee.yodlee_widget
msgid "Synchronization process completed"
msgstr "Processus de synchronisation complété"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#: code:addons/account_yodlee/models/yodlee.py:0
#: code:addons/account_yodlee/models/yodlee.py:0
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Timeout: the server did not reply within 30s"
msgstr "Délai écoulé: le serveur n'a pas répondu dans les 30 secondes"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Update Request Canceled(405):Your account was not updated because you "
"canceled the request."
msgstr ""
"Demande de mise à jour annulée (405): votre compte n’a pas été mis à jour, "
"car vous avez annulé la demande."

#. module: account_yodlee
#: model:ir.model.fields.selection,name:account_yodlee.selection__account_online_provider__provider_type__yodlee
msgid "Yodlee"
msgstr "Yodlee"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_account_online_journal__yodlee_account_status
msgid "Yodlee Account Status"
msgstr "État du compte Yodlee"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_account_online_journal__yodlee_status_code
msgid "Yodlee Status Code"
msgstr "Code d’état Yodlee"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_res_company__yodlee_user_access_token
msgid "Yodlee access token"
msgstr "Jeton d'accès Yodlee"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_res_company__yodlee_user_login
msgid "Yodlee login"
msgstr "Identifiant Yodlee"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_res_company__yodlee_user_password
msgid "Yodlee password"
msgstr "Mot de passe Yodlee"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_res_company__yodlee_access_token
msgid "access_token"
msgstr "jeton_access"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "message: %s"
msgstr "message: %s"
