# Translation of Odoo Server.
# This file contains the translation of the following modules:
# 	* account_yodlee
# 
# Translators:
# Martin Trigaux, 2019
# Vasiliy Korobatov <korobatov@gmail.com>, 2019
# Ivan Yelizariev <yelizariev@it-projects.info>, 2019
# 
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server saas~12.5+e\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-08-26 08:04+0000\n"
"PO-Revision-Date: 2019-08-26 09:34+0000\n"
"Last-Translator: Ivan Yelizariev <yelizariev@it-projects.info>, 2019\n"
"Language-Team: Russian (https://www.transifex.com/odoo/teams/41243/ru/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"
"Language: ru\n"
"Plural-Forms: nplurals=4; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<12 || n%100>14) ? 1 : n%10==0 || (n%10>=5 && n%10<=9) || (n%100>=11 && n%100<=14)? 2 : 3);\n"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "(Diagnostic: %r for URL %s)"
msgstr "(Диагностический: %r для URL-адреса %s)"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Account"
msgstr "Счёт"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Account Already Registered (436):Your Auto-Registration could not be "
"completed because the site reports that your account is already registered."
"  Please log in to the site to confirm and then complete the site addition "
"process with the correct login information."
msgstr ""
"Учетная запись уже зарегистрирована (436): Ваша автоматическая регистрация "
"не может быть завершена, поскольку сайт сообщает, что ваша учетная запись "
"уже зарегистрирована. Войдите на сайт, чтобы подтвердить, а затем заполните "
"процесс добавления сайта с правильной информацией для входа."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Account Locked (407): We could not update your account because it appears "
"your account has been locked. This usually results from too many "
"unsuccessful login attempts in a short period of time. Please visit the site"
" or contact its customer support to resolve this issue.  Once done, please "
"update your account credentials in case they are changed."
msgstr ""
"Учетная запись заблокирована (407): мы не смогли обновить вашу учетную "
"запись, поскольку, похоже, ваша учетная запись заблокирована. Обычно это "
"происходит из-за слишком большого числа неудачных попыток входа в систему за"
" короткий период времени. Пожалуйста, посетите сайт или обратитесь в службу "
"поддержки, чтобы решить эту проблему. После этого обновите свои учетные "
"данные в случае их изменения."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Account Not Found(408): We're sorry, we couldn't find any accounts for you "
"at the site. Please log in at the site and confirm that your account is set "
"up, then try again."
msgstr ""
"Аккаунт не найден (408): К сожалению, мы не смогли найти для вас учетные "
"записи на этом сайте. Войдите на сайт и подтвердите, что ваша учетная запись"
" настроена, а затем повторите попытку."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Account Reported Closed (422): We were unable to update your account "
"information because it appears one or more of your related accounts have "
"been closed.  Please deactivate or delete the relevant account and try "
"again."
msgstr ""
"Учетная запись, о которой сообщается. Закрыто (422). Нам не удалось обновить"
" информацию о вашей учетной записи, так как кажется, что одна или несколько "
"ваших связанных учетных записей были закрыты. Дезактивируйте или удалите "
"соответствующую учетную запись и повторите попытку."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Account Type Not Supported(417):The type of account we found is not "
"currently supported.  Please remove this site and add as a  manual account."
msgstr ""
"Тип учетной записи не поддерживается (417): тип найденной нами учетной "
"записи в настоящее время не поддерживается. Удалите этот сайт и добавьте его"
" вручную."

#. module: account_yodlee
#: model:ir.model.fields,help:account_yodlee.field_account_online_journal__yodlee_account_status
msgid "Active/Inactive on Yodlee system"
msgstr "Активно/неактивно в системе "

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "An Error has occurred (code %s)"
msgstr "Произошла Ошибка (код %s)"

#. module: account_yodlee
#: model:ir.model,name:account_yodlee.model_res_company
msgid "Companies"
msgstr "Компании"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Could not make sense of parameters: %s"
msgstr "Невозможно понять параметры:% s"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Credential Re-Verification Required (402): We could not update your account "
"because your username and/or password were reported to be incorrect.  Please"
" re-verify your username and password."
msgstr ""
"Требуется повторная проверка учетных данных (402): мы не смогли обновить "
"вашу учетную запись, так как ваше имя пользователя и / или пароль были "
"указаны неверно. Подтвердите свое имя пользователя и пароль."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Credential Re-Verification Required (420):The site has merged with another. "
"Please re-verify your credentials at the site and update the same."
msgstr ""
"Требуется повторная проверка учетных данных (420): сайт слился с другим. "
"Повторно проверьте свои учетные данные на сайте и обновите его."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Error %s, message: %s"
msgstr "Ошибка% s, сообщение:% s"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Error %s, message: %s, reference code: %s"
msgstr "Ошибка %s, сообщение: %s, код ссылки: %s"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Home Value Not Found (511): The site is unable to provide home value for "
"your property. We suggest you to delete this site."
msgstr ""
"Главная ценность не найдена (511): сайт не может обеспечить домашнюю "
"ценность для вашей недвижимости. Мы предлагаем вам удалить этот сайт."

#. module: account_yodlee
#: model:ir.model,name:account_yodlee.model_account_online_journal
msgid "Interface for Online Account Journal"
msgstr "Интерфейс для онлайн журнала счета"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Invalid Language Setting (421): The language setting for your site account "
"is not English. Please visit the site and change the language setting to "
"English."
msgstr ""
"Недопустимая языковая настройка (421). Языковой параметр для учетной записи "
"сайта не является английским. Перейдите на сайт и измените настройку языка "
"на английский."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Additional Authentication Enrollment Required (521) : Please "
"enroll in the new security authentication system, <Account Name> has "
"introduced. Ensure your account settings in <Cobrand> are updated with this "
"information."
msgstr ""
"Ошибка MFA: Требуется дополнительная аутентификация (521): Пожалуйста, "
"зарегистрируйтесь в новой системе аутентификации безопасности, <Account "
"Name> Представила. Убедитесь, что настройки вашей учетной записи <Cobrand> "
"Будут обновлены с этой информацией."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Authentication Information Expired (524):We're sorry, the "
"authentication information you provided has expired. Please try again."
msgstr ""
"Ошибка MFA: информация об аутентификации истек (524): мы сожалеем, срок "
"действия указанной вами аутентификационной информации истек. Пожалуйста, "
"попробуйте еще раз."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Authentication Information Incorrect (520):We're sorry, the site "
"indicates that the additional authentication information you provided is "
"incorrect. Please try updating your account again."
msgstr ""
"Ошибка MFA: информация об аутентификации неверна (520): Извините, сайт "
"указывает, что предоставленная вами дополнительная информация об "
"аутентификации неверна. Попробуйте обновить свою учетную запись еще раз."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Authentication Information Incorrect (523):We're sorry, the "
"authentication information you  provided is incorrect. Please try again."
msgstr ""
"Ошибка MFA: информация об аутентификации неверна (523): К сожалению, "
"предоставленная вами информация о проверке подлинности неверна. Пожалуйста, "
"попробуйте еще раз."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Authentication Information Required (519): Your account was not "
"updated as your authentication information like security question and answer"
" was unavailable or incomplete. Please update your account settings."
msgstr ""
"Ошибка MFA: требуется информация о проверке подлинности (519). Ваша учетная "
"запись не обновлялась, поскольку ваши данные аутентификации, такие как "
"секретный вопрос и ответ, были недоступны или не были заполнены. Обновите "
"настройки своей учетной записи."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Authentication Information Unavailable (518):Your account was not"
" updated as the required additional authentication information was "
"unavailable. Please try now."
msgstr ""
"Ошибка MFA: информация об аутентификации недоступна (518). Ваша учетная "
"запись не была обновлена, поскольку требуемая дополнительная информация об "
"аутентификации была недоступна. Попробуйте прямо сейчас."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Credential Re-Verification Required (526): We could not update "
"your account because your username/password or additional security "
"credentials are incorrect. Please try again."
msgstr ""
"Ошибка MFA: Требуется повторная проверка учетных данных (526): Мы не смогли "
"обновить вашу учетную запись, потому что ваши имя пользователя / пароль или "
"дополнительные учетные данные безопасности неверны. Пожалуйста, попробуйте "
"еще раз."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Problem Updating Account (525): We could not update your account "
"for technical reasons. This type of error is usually resolved in a few days."
" We apologize for the inconvenience. Please try again later."
msgstr ""
"Ошибка MFA: ошибка обновления учетной записи (525). Мы не смогли обновить "
"вашу учетную запись по техническим причинам. Этот тип ошибки обычно решается"
" через несколько дней. Приносим свои извинения за доставленные неудобства. "
"Пожалуйста, повторите попытку позже."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Request Timed Out (522) :Your request has timed out as the "
"required security information was unavailable or was not provided within the"
" expected time. Please try again."
msgstr ""
"Ошибка MFA: запрос по тайм-ауту (522): время ожидания вашего запроса "
"истекло, так как требуемая информация безопасности была недоступна или не "
"была предоставлена ​​в течение ожидаемого времени. Пожалуйста, попробуйте "
"еще раз."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Site Device Information Expired(509): We're sorry, we can't "
"update your account because your token is no longer valid at the site. "
"Please update your information and try again, or contact customer support."
msgstr ""
"Ошибка MFA: информация об устройстве на устройстве истек (509): К сожалению,"
" мы не можем обновить вашу учетную запись, так как ваш токен больше "
"недействителен на сайте. Обновите информацию и повторите попытку или "
"обратитесь в службу поддержки."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Multiple User Logins(416): We attempted to update your account, but another "
"session was already established at the same time.  If you are currently "
"logged on to this account directly, please log off and try after some time"
msgstr ""
"Несколько логинов пользователей (416): Мы попытались обновить вашу учетную "
"запись, но другой сеанс уже был установлен в одно и то же время. Если вы "
"вошли в этот аккаунт напрямую, выйдите из системы и повторите попытку через "
"некоторое время"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"New Login Information Required(506):We're sorry, to log in to this site, you"
" need to provide additional information. Please update your account and try "
"again."
msgstr ""
"Требуется ввести новую регистрационную информацию (506): К сожалению, для "
"входа на этот сайт вам необходимо предоставить дополнительную информацию. "
"Обновите свою учетную запись и повторите попытку."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"No Account Found (423): We were unable to detect an account. Please verify "
"that you account information is available at this time and If the problem "
"persists, please contact customer support at online@odoo.com for further "
"assistance."
msgstr ""
"Учетная запись не найдена (423): нам не удалось обнаружить учетную запись. "
"Убедитесь, что информация об учетной записи доступна в это время. Если "
"проблема не устранена, обратитесь в службу поддержки по адресу: "
"online@odoo.com для получения дополнительной помощи."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"No Payees Found(512):Your request cannot be completed as no payees were "
"found in your account."
msgstr ""
"Нет получателей платежей (512): ваш запрос не может быть выполнен, так как в"
" вашем аккаунте не было обнаружено получателей."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Online institution"
msgstr "онлайн учреждение"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Please configure an email in the company settings."
msgstr "Настройте электронную почту в настройках компании."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account (406): We could not update your account because the"
" site requires you to perform some additional action. Please visit the site "
"or contact its customer support to resolve this issue. Once done, please "
"update your account credentials in case they are changed else try again."
msgstr ""
"Проблема с обновлением учетной записи (406). Мы не смогли обновить вашу "
"учетную запись, поскольку на этом сайте требуется выполнить некоторые "
"дополнительные действия. Пожалуйста, посетите сайт или обратитесь в службу "
"поддержки, чтобы решить эту проблему. После этого обновите свои учетные "
"данные, если они были изменены. Повторите попытку."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account (517): We are sorry, there was a technical problem "
"updating your account. Please try again."
msgstr ""
"Проблема обновления аккаунта (517). К сожалению, возникла техническая "
"проблема с обновлением аккаунта. Пожалуйста попробуйте еще раз."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(401):We're sorry, your request timed out. Please "
"try again."
msgstr ""
"Проблема с обновлением учетной записи (401): Сожалеем, срок вашего запроса "
"истек. Пожалуйста, попробуйте еще раз."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(403):We're sorry, there was a technical problem "
"updating your account. This kind of error is usually resolved in a few days."
" Please try again later."
msgstr ""
"Проблема с обновлением учетной записи (403): К сожалению, при обновлении "
"вашей учетной записи возникла техническая проблема. Такая ошибка обычно "
"устраняется через несколько дней. Пожалуйста, повторите попытку позже."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(404):We're sorry, there was a technical problem "
"updating your account. Please try again later."
msgstr ""
"Проблема с обновлением учетной записи (404): К сожалению, при обновлении "
"вашей учетной записи возникла техническая проблема. Пожалуйста, повторите "
"попытку позже."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(409): We could not update your account because the "
"end site is experiencing technical difficulties."
msgstr ""
"Проблема с обновлением учетной записи (409. Мы не смогли обновить вашу "
"учетную запись, так как сайт испытывает технические трудности."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(412): We could not update your account because the "
"site is experiencing technical difficulties."
msgstr ""
"Проблема с обновлением учетной записи (412). Мы не смогли обновить вашу "
"учетную запись, так как сайт испытывает технические трудности."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(413):We're sorry, we couldn't update your account "
"at the site because of a technical issue. This type of problem is usually "
"resolved in a few days. Please try again later."
msgstr ""
"Проблема с обновлением учетной записи (413): К сожалению, мы не смогли "
"обновить вашу учетную запись на сайте из-за технической проблемы. Этот тип "
"проблемы обычно решается через несколько дней. Пожалуйста, повторите попытку"
" позже."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(415): We could not update your account because the "
"site is experiencing technical difficulties."
msgstr ""
"Проблема с обновлением учетной записи (415): Мы не смогли обновить вашу "
"учетную запись, так как у сайта возникли технические проблемы."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(418): We could not update your account because the "
"site is experiencing technical difficulties. Please try later."
msgstr ""
"Проблема с обновлением учетной записи (418). Мы не смогли обновить вашу "
"учетную запись, так как у сайта возникли технические проблемы. Пожалуйста, "
"попробуйте позднее."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(419):We're sorry, we couldn't update your account "
"because of unexpected variations at the site. This kind of problem is "
"usually resolved in a few days. Please try again later."
msgstr ""
"Проблема с обновлением учетной записи (419): К сожалению, мы не смогли "
"обновить вашу учетную запись из-за неожиданных изменений на сайте. Обычно "
"такая проблема решается через несколько дней. Пожалуйста, повторите попытку "
"позже."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(425): We could not update your account because the "
"site is experiencing technical difficulties. Please try later."
msgstr ""
"Проблема с обновлением учетной записи (425). Мы не смогли обновить вашу "
"учетную запись, так как у сайта возникли технические проблемы. Пожалуйста, "
"попробуйте позднее."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(426): We could not update your account for "
"technical reasons. This type of error is usually resolved in a few days. We "
"apologize for the inconvenience."
msgstr ""
"Проблема с обновлением учетной записи (426). Мы не смогли обновить вашу "
"учетную запись по техническим причинам. Этот тип ошибки обычно решается "
"через несколько дней. Приносим свои извинения за доставленные неудобства."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(507):We're sorry, Yodlee has just started providing"
" data updates for this site, and it may take a few days to be successful as "
"we get started. Please try again later."
msgstr ""
"Проблема с обновлением учетной записи (507): мы просим прощения, Yodlee "
"только что начал предоставлять обновления данных для этого сайта, и для "
"начала работы может потребоваться несколько дней. Пожалуйста, повторите "
"попытку позже."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Property Record Not Found (510): The site is unable to find any property "
"information for your address. Please verify if the property address you have"
" provided is correct."
msgstr ""
"Запись свойств не найдена (510): Сайт не может найти информацию об объекте "
"для вашего адреса. Проверьте правильность указанного адреса собственности."

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_account_online_provider__provider_type
msgid "Provider Type"
msgstr "Тип поставщика"

#. module: account_yodlee
#: model:ir.model,name:account_yodlee.model_account_online_provider
msgid "Provider for online account synchronization"
msgstr "Поставщик для синхронизации счета онлайн"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Re-Verification Required (429): We could not update your account due to the "
"site requiring you to verify your personal information. Please log in to the"
" site and update the fields required."
msgstr ""
"Необходима повторная проверка (429). Мы не смогли обновить вашу учетную "
"запись из-за того, что на сайте требуется подтвердить вашу личную "
"информацию. Войдите на сайт и обновите необходимые поля."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Re-verification Required (427): We could not update your account due to the "
"site requiring you to view a new promotion. Please log in to the site and "
"click through to your account overview page to update the account.  We "
"apologize for the inconvenience."
msgstr ""
"Требуется повторная проверка (427). Мы не смогли обновить вашу учетную "
"запись из-за того, что сайт требует, чтобы вы просматривали новую рекламную "
"акцию. Войдите на сайт и перейдите на страницу обзора своей учетной записи, "
"чтобы обновить учетную запись. Приносим свои извинения за доставленные "
"неудобства."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Re-verification Required (428): We could not update your account due to the "
"site requiring you to accept a new Terms & Conditions. Please log in to the "
"site and read and accept the T&C."
msgstr ""
"Необходима повторная проверка (428). Мы не смогли обновить вашу учетную "
"запись из-за того, что на сайте требуется принять новые условия. Войдите на "
"сайт и прочитайте и примите Условия и Положения."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Registration Requires Attention (433): Auto registration is not complete. "
"Please complete your registration at the end site. Once completed, please "
"complete adding this account."
msgstr ""
"Регистрация Требуется внимание (433): Авторегистрация не завершена. "
"Пожалуйста, завершите регистрацию на конечном сайте. Закончив, добавьте эту "
"учетную запись."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Registration Requires Attention (434): Your Auto-Registration could not be "
"completed and requires further input from you.  Please re-verify your "
"registration information to complete the process."
msgstr ""
"Регистрация Требуется внимание (434): Ваша автоматическая регистрация не "
"может быть завершена и требует от вас дополнительных сведений. Повторите "
"проверку регистрационной информации, чтобы завершить процесс."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Registration Requires Attention (435): Your Auto-Registration could not be "
"completed and requires further input from you.  Please re-verify your "
"registration information to complete the process."
msgstr ""
"Регистрация Требуется внимание (435): Ваша авторегистрация не может быть "
"выполнена и требует от вас дополнительных сведений. Повторите проверку "
"регистрационной информации, чтобы завершить процесс."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Request Timed Out (508): We are sorry, your request timed out due to "
"technical reasons. Please try again."
msgstr ""
"Запрос по времени ожидания (508): к сожалению, ваш запрос истек по "
"техническим причинам. Пожалуйста, попробуйте еще раз."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Requested Account Type Not Found (414): We could not find your requested "
"account. You may have selected a similar site under a different category by "
"accident in which case you should select the correct site."
msgstr ""
"Тип запрашиваемой учетной записи не найден (414): мы не смогли найти вашу "
"запрашиваемую учетную запись. Вы случайно выбрали подобный сайт под другой "
"категорией, и в этом случае вам следует выбрать правильный сайт."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Server not reachable, please try again later"
msgstr "Сервер недоступен. Повторите попытку позже"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Site Down for Maintenance(424):We were unable to update your account as the "
"site is temporarily down for maintenance. We apologize for the "
"inconvenience.  This problem is typically resolved in a few hours. Please "
"try later."
msgstr ""
"Сайт закрыт на техническое обслуживание (424): Мы не смогли обновить вашу "
"учетную запись, так как сайт временно недоступен для обслуживания. Приносим "
"свои извинения за доставленные неудобства. Обычно эта проблема устраняется "
"через несколько часов. Пожалуйста, попробуйте позднее."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Site No Longer Available (411):The site no longer provides online services "
"to its customers.  Please delete this account."
msgstr ""
"Сайт больше не доступен (411): сайт больше не предоставляет онлайн-услуги "
"своим клиентам. Удалите эту учетную запись."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Site No Longer Supported (430):This site is no longer supported for data "
"updates. Please deactivate or delete your account. We apologize for the "
"inconvenience."
msgstr ""
"Сайт больше не поддерживается (430): Этот сайт больше не поддерживается для "
"обновления данных. Деактивируйте или удалите свою учетную запись. Приносим "
"свои извинения за доставленные неудобства."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Site Not Supported (505): We currently does not support the security system "
"used by this site. We apologize for any inconvenience. Check back "
"periodically if this situation has changed."
msgstr ""
"Сайт не поддерживается (505): В настоящее время мы не поддерживаем систему "
"безопасности, используемую этим сайтом. Мы приносим свои извинения за "
"доставленные неудобства. Периодически проверяйте, изменилась ли эта "
"ситуация."

#. module: account_yodlee
#: model:ir.actions.client,name:account_yodlee.yodlee_widget
msgid "Synchronization process completed"
msgstr "Процесс синхронизации завершено"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#: code:addons/account_yodlee/models/yodlee.py:0
#: code:addons/account_yodlee/models/yodlee.py:0
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Timeout: the server did not reply within 30s"
msgstr "Задержка: сервер не отвечает более 30 сек."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Update Request Canceled(405):Your account was not updated because you "
"canceled the request."
msgstr ""
"Обновление запроса отменено (405): Ваш аккаунт не был обновлен, потому что "
"вы отменили запрос."

#. module: account_yodlee
#: model:ir.model.fields.selection,name:account_yodlee.selection__account_online_provider__provider_type__yodlee
msgid "Yodlee"
msgstr "Йодле"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_account_online_journal__yodlee_account_status
msgid "Yodlee Account Status"
msgstr "Статус учета Yodlee"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_account_online_journal__yodlee_status_code
msgid "Yodlee Status Code"
msgstr "Статус кода Yodlee"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_res_company__yodlee_user_access_token
msgid "Yodlee access token"
msgstr "Токен доступа Yodlee"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_res_company__yodlee_user_login
msgid "Yodlee login"
msgstr "Логин Yodlee"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_res_company__yodlee_user_password
msgid "Yodlee password"
msgstr "Пароль Yodlee"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_res_company__yodlee_access_token
msgid "access_token"
msgstr "access_token"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "message: %s"
msgstr "сообщение:% s"
